"""
Test Framework - Automated testing for M365 agents
"""

import json
import os
from typing import Dict, Any, List, Optional
from pathlib import Path
from datetime import datetime


class TestFramework:
    """Testing framework for M365 agents with automated scenarios."""
    
    def __init__(self, verbose: bool = False):
        """Initialize test framework.
        
        Args:
            verbose: Enable verbose output
        """
        self.verbose = verbose
        self.test_results = []
        
    def create_test_suite(self, agent_path: str) -> str:
        """Create automated test suite for an agent.
        
        Args:
            agent_path: Path to agent directory
            
        Returns:
            Path to generated test file
        """
        print(f"\n🧪 Creating test suite for agent: {agent_path}\n")
        
        agent_dir = Path(agent_path)
        if not agent_dir.exists():
            print(f"❌ Agent directory not found: {agent_path}")
            return ""
        
        # Load agent configuration
        config_file = agent_dir / "declarativeAgent.json"
        if not config_file.exists():
            print(f"❌ Agent configuration not found: {config_file}")
            return ""
        
        with open(config_file, 'r') as f:
            agent_config = json.load(f)
        
        # Generate test file
        test_file_path = agent_dir / "test_agent.py"
        test_content = self._generate_test_content(agent_config)
        
        with open(test_file_path, 'w') as f:
            f.write(test_content)
        
        print(f"✅ Test suite created: {test_file_path}")
        print(f"\n📋 Generated tests:")
        print(f"   • test_agent_config_valid()")
        print(f"   • test_required_fields()")
        print(f"   • test_capabilities_configured()")
        print(f"   • test_conversation_starters()")
        print(f"   • test_instructions_exist()")
        
        if agent_config.get("capabilities"):
            print(f"   • test_capability_configuration()")
        
        print(f"\n💡 Run tests with: pytest {test_file_path}")
        
        return str(test_file_path)
    
    def _generate_test_content(self, agent_config: Dict[str, Any]) -> str:
        """Generate test file content.
        
        Args:
            agent_config: Agent configuration
            
        Returns:
            Test file content
        """
        agent_name = agent_config.get("name", "Agent")
        
        return f'''"""
Automated tests for {agent_name}
Generated by M365 Agent Toolkit Assistant Test Framework
"""

import json
import pytest
from pathlib import Path


class Test{agent_name.replace(" ", "")}:
    """Test suite for {agent_name}."""
    
    @pytest.fixture
    def agent_config(self):
        """Load agent configuration."""
        config_path = Path(__file__).parent / "declarativeAgent.json"
        with open(config_path, 'r') as f:
            return json.load(f)
    
    def test_agent_config_valid(self, agent_config):
        """Test that agent configuration is valid JSON."""
        assert agent_config is not None
        assert isinstance(agent_config, dict)
    
    def test_required_fields(self, agent_config):
        """Test that all required fields are present."""
        required_fields = ["$schema", "version", "name", "description"]
        
        for field in required_fields:
            assert field in agent_config, f"Missing required field: {{field}}"
    
    def test_schema_url(self, agent_config):
        """Test that schema URL is correct."""
        expected_schema = "https://developer.microsoft.com/json-schemas/copilot/declarative-agent/v1.0/schema.json"
        assert agent_config.get("$schema") == expected_schema
    
    def test_version(self, agent_config):
        """Test that version is correct."""
        assert agent_config.get("version") == "v1.0"
    
    def test_name_length(self, agent_config):
        """Test that name is within length limit."""
        name = agent_config.get("name", "")
        assert len(name) <= 100, f"Name exceeds 100 characters: {{len(name)}}"
        assert len(name) > 0, "Name cannot be empty"
    
    def test_description_length(self, agent_config):
        """Test that description is within length limit."""
        description = agent_config.get("description", "")
        assert len(description) <= 1000, f"Description exceeds 1000 characters: {{len(description)}}"
        assert len(description) > 0, "Description cannot be empty"
    
    def test_capabilities_configured(self, agent_config):
        """Test that capabilities are properly configured."""
        capabilities = agent_config.get("capabilities", [])
        
        if capabilities:
            assert isinstance(capabilities, list)
            for cap in capabilities:
                assert "name" in cap, "Capability missing 'name' field"
                assert cap["name"] in [
                    "WebSearch", "MicrosoftGraph", "OneDriveAndSharePoint", "GraphConnectors"
                ], f"Unknown capability: {{cap['name']}}"
    
    def test_conversation_starters(self, agent_config):
        """Test that conversation starters are valid."""
        starters = agent_config.get("conversation_starters", [])
        
        if starters:
            assert isinstance(starters, list)
            assert len(starters) >= 1, "Should have at least one conversation starter"
            assert len(starters) <= 5, "Should not exceed 5 conversation starters"
            
            for starter in starters:
                assert "title" in starter
                assert "text" in starter
                assert len(starter["title"]) > 0
                assert len(starter["text"]) > 0
    
    def test_instructions_exist(self, agent_config):
        """Test that instructions are provided."""
        instructions = agent_config.get("instructions", "")
        
        assert instructions, "Instructions should not be empty"
        
        # Check if using external file
        if instructions.startswith("$[file("):
            instructions_file = Path(__file__).parent / "instructions.txt"
            assert instructions_file.exists(), "Instructions file not found"
    
    def test_instructions_length(self, agent_config):
        """Test that instructions are within length limit."""
        instructions = agent_config.get("instructions", "")
        
        # Only check length if not using external file
        if not instructions.startswith("$[file("):
            assert len(instructions) <= 8000, f"Instructions exceed 8000 characters: {{len(instructions)}}"
    
    def test_capability_microsoft_graph_scopes(self, agent_config):
        """Test that MicrosoftGraph capability has valid scopes."""
        capabilities = agent_config.get("capabilities", [])
        
        valid_scopes = [
            "User.Read", "User.ReadBasic.All", "Mail.Read", "Mail.ReadBasic",
            "Calendars.Read", "Calendars.ReadBasic", "Files.Read.All",
            "Sites.Read.All", "Chat.Read", "Team.ReadBasic.All"
        ]
        
        for cap in capabilities:
            if cap.get("name") == "MicrosoftGraph":
                scopes = cap.get("allowed_scopes", [])
                for scope in scopes:
                    assert scope in valid_scopes, f"Invalid scope: {{scope}}"
    
    def test_no_hardcoded_secrets(self, agent_config):
        """Test that configuration doesn't contain hardcoded secrets."""
        config_str = json.dumps(agent_config).lower()
        
        # Check for common secret patterns
        forbidden_patterns = ["password", "secret", "api_key", "apikey", "token"]
        
        for pattern in forbidden_patterns:
            assert pattern not in config_str, f"Possible hardcoded secret found: {{pattern}}"


# Scenario-based tests
class Test{agent_name.replace(" ", "")}Scenarios:
    """Scenario-based tests for {agent_name}."""
    
    @pytest.fixture
    def agent_config(self):
        """Load agent configuration."""
        config_path = Path(__file__).parent / "declarativeAgent.json"
        with open(config_path, 'r') as f:
            return json.load(f)
    
    def test_scenario_basic_greeting(self, agent_config):
        """Test basic greeting scenario."""
        # This would test actual agent responses in integration testing
        # For now, verify configuration supports this scenario
        assert agent_config.get("instructions"), "Agent should have instructions for handling greetings"
    
    def test_scenario_help_request(self, agent_config):
        """Test help request scenario."""
        # Verify agent has conversation starters or help guidance
        starters = agent_config.get("conversation_starters", [])
        instructions = agent_config.get("instructions", "")
        
        assert starters or "help" in instructions.lower(), "Agent should provide help functionality"
    
    def test_scenario_capability_usage(self, agent_config):
        """Test that agent can use configured capabilities."""
        capabilities = agent_config.get("capabilities", [])
        
        if capabilities:
            # Verify instructions mention using capabilities
            instructions = agent_config.get("instructions", "")
            # At least one capability should be referenced in instructions
            assert len(instructions) > 0, "Instructions should explain capability usage"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
'''
    
    def run_tests(self, test_file: str) -> Dict[str, Any]:
        """Run tests and return results.
        
        Args:
            test_file: Path to test file
            
        Returns:
            Test results dictionary
        """
        print(f"\n🧪 Running tests: {test_file}\n")
        
        import subprocess
        
        try:
            result = subprocess.run(
                ["pytest", test_file, "-v", "--tb=short"],
                capture_output=True,
                text=True,
                timeout=30
            )
            
            print(result.stdout)
            if result.stderr:
                print(result.stderr)
            
            return {
                "success": result.returncode == 0,
                "output": result.stdout,
                "errors": result.stderr
            }
        except FileNotFoundError:
            print("❌ pytest not installed. Install with: pip install pytest")
            return {"success": False, "output": "", "errors": "pytest not found"}
        except Exception as e:
            print(f"❌ Error running tests: {e}")
            return {"success": False, "output": "", "errors": str(e)}
    
    def generate_test_report(self, results: List[Dict[str, Any]], output_file: str = "test_report.html"):
        """Generate HTML test report.
        
        Args:
            results: List of test results
            output_file: Output file path
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        html_content = f"""<!DOCTYPE html>
<html>
<head>
    <title>M365 Agent Test Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; }}
        h1 {{ color: #0078d4; }}
        .summary {{ background: #f0f0f0; padding: 15px; border-radius: 5px; margin: 20px 0; }}
        .test {{ border: 1px solid #ddd; padding: 10px; margin: 10px 0; border-radius: 3px; }}
        .pass {{ border-left: 4px solid #28a745; }}
        .fail {{ border-left: 4px solid #dc3545; }}
        .timestamp {{ color: #666; font-size: 0.9em; }}
    </style>
</head>
<body>
    <h1>🧪 M365 Agent Test Report</h1>
    <p class="timestamp">Generated: {timestamp}</p>
    
    <div class="summary">
        <h2>Summary</h2>
        <p>Total tests: {len(results)}</p>
        <p>Passed: {sum(1 for r in results if r.get('success'))}</p>
        <p>Failed: {sum(1 for r in results if not r.get('success'))}</p>
    </div>
    
    <h2>Test Results</h2>
"""
        
        for i, result in enumerate(results, 1):
            status_class = "pass" if result.get("success") else "fail"
            status_text = "✅ PASSED" if result.get("success") else "❌ FAILED"
            
            html_content += f"""
    <div class="test {status_class}">
        <h3>Test {i}: {status_text}</h3>
        <pre>{result.get('output', 'No output')}</pre>
    </div>
"""
        
        html_content += """
</body>
</html>
"""
        
        with open(output_file, 'w') as f:
            f.write(html_content)
        
        print(f"\n📊 Test report generated: {output_file}")
    
    def interactive_mode(self):
        """Run test framework in interactive mode."""
        while True:
            print("\n" + "="*80)
            print("🧪 TEST FRAMEWORK")
            print("="*80)
            print("\n1. Create test suite for agent")
            print("2. Run tests")
            print("3. Generate test report")
            print("4. View test best practices")
            print("5. Back to main menu")
            
            choice = input("\nSelect option (1-5): ").strip()
            
            if choice == "1":
                agent_path = input("\nEnter agent directory path: ").strip()
                self.create_test_suite(agent_path)
            elif choice == "2":
                test_file = input("\nEnter test file path: ").strip()
                result = self.run_tests(test_file)
                self.test_results.append(result)
            elif choice == "3":
                if self.test_results:
                    output_file = input("\nOutput file (test_report.html): ").strip() or "test_report.html"
                    self.generate_test_report(self.test_results, output_file)
                else:
                    print("\n❌ No test results available. Run tests first.")
            elif choice == "4":
                self._show_best_practices()
            elif choice == "5":
                break
            else:
                print("Invalid option")
            
            input("\nPress Enter to continue...")
    
    def _show_best_practices(self):
        """Show testing best practices."""
        print("\n" + "="*80)
        print("📚 TESTING BEST PRACTICES")
        print("="*80 + "\n")
        
        practices = [
            ("Test Configuration Validity", "Verify JSON schema compliance and required fields"),
            ("Test Field Constraints", "Check name/description length limits (100/1000 chars)"),
            ("Test Capabilities", "Validate capability names and configurations"),
            ("Test Conversation Starters", "Ensure 1-5 starters with proper format"),
            ("Test Instructions", "Verify instructions exist and are within 8000 char limit"),
            ("Test Security", "Check for hardcoded secrets or sensitive data"),
            ("Scenario Testing", "Test common user scenarios and edge cases"),
            ("Integration Testing", "Test with actual Teams Toolkit deployment"),
            ("Performance Testing", "Verify response times and resource usage"),
            ("User Acceptance Testing", "Get feedback from real users")
        ]
        
        for i, (practice, description) in enumerate(practices, 1):
            print(f"{i}. {practice}")
            print(f"   {description}\n")
